import conexao_fb

# Consulta SQL
sql_query = """
-- Sua consulta SQL completa aqui
SELECT
        FPG.DTFINAL AS DATA,
        EPG.EMP_CODIGO AS CDEMPRESA,
		EST.CODIGO AS CDESTABELECIMENTO,
		EST.NOME AS NMESTABELECIMENTO,
		LOT.CODIGO AS CDLOTACAO,
		LOT.NOME AS NMLOTACAO,
        EFP.EVE_CODIGO AS CDEVENTO,
		EVE.NOME AS NMEVENTO,
		REPLACE(SUM(
            CASE
                WHEN EVE.INFPROVDESC = 1 then EFP.VALOR else -efp.valor end
		    ), '.', ',') AS VLEVENTO,

         CASE
            WHEN EVE.INFPROVDESC = 0 THEN 'BASE'
            WHEN EVE.INFPROVDESC = 1 THEN 'PROVENTO'
         ELSE 'DESCONTO' END  AS TPEVENTO,
         TFO.DESCRICAO  AS ORIGEM

FROM  EFO
    JOIN EFP ON EFP.EMP_CODIGO = EFO.EMP_CODIGO AND EFP.EFO_FOL_SEQ = EFO.FOL_SEQ AND EFP.EFO_EPG_CODIGO = EFO.EPG_CODIGO
    JOIN FOL ON EFO.EMP_CODIGO = FOL.EMP_CODIGO AND EFO.FOL_SEQ = FOL.SEQ
    JOIN EPG ON EFO.EMP_CODIGO = EPG.EMP_CODIGO AND EFO.EPG_CODIGO = EPG.CODIGO
    JOIN EVE ON EVE.EMP_CODIGO = EFP.EMP_CODIGO AND EVE.CODIGO = EFP.EVE_CODIGO
    JOIN FPG ON FPG.EMP_CODIGO = EPG.EMP_CODIGO  AND FPG.FOL_SEQ = FOL.SEQ
	JOIN SEP ON SEP.EMP_CODIGO = EFO.EMP_CODIGO AND SEP.DATA = EFO.SEP_DATA AND SEP.EPG_CODIGO = EFO.EPG_CODIGO
	JOIN EST ON EST.EMP_CODIGO = SEP.EMP_CODIGO AND SEP.EST_CODIGO = EST.CODIGO
	JOIN LOT ON LOT.EMP_CODIGO = SEP.EMP_CODIGO AND LOT.CODIGO = SEP.LOT_CODIGO
	JOIN TFO ON TFO.CODIGO = FOL.FOLHA
WHERE
    FOL.ENCERRADA = 'S'
  and EVE.INFPROVDESC <> 0
AND FOL.FOLHA IN (2,17,3)
---AND FOL.EMP_CODIGO = '0009'
AND EXTRACT(YEAR FROM FPG.DTFINAL) = EXTRACT(YEAR FROM CURRENT_DATE)
AND EXTRACT(MONTH FROM FPG.DTFINAL) = EXTRACT(MONTH FROM CURRENT_DATE)-1

GROUP BY
    FPG.DTFINAL,
    EPG.EMP_CODIGO,
	EST.CODIGO,
	EST.NOME,
	LOT.CODIGO,
	LOT.NOME,
    EFP.EVE_CODIGO,
	EVE.NOME,
	EVE.INFPROVDESC,
	TFO.DESCRICAO


UNION ALL

-- ADIANTAMENTO
SELECT
        FOL.DTCALCULO AS DATA,
        EPG.EMP_CODIGO AS CDEMPRESA,
		EST.CODIGO AS CDESTABELECIMENTO,
		EST.NOME AS NMESTABELECIMENTO,
		LOT.CODIGO AS CDLOTACAO,
		LOT.NOME AS NMLOTACAO,
        EFP.EVE_CODIGO AS CDEVENTO,
		EVE.NOME AS NMEVENTO,
		REPLACE(SUM(EFP.VALOR), '.', ',') AS VLEVENTO,
         CASE
            WHEN EVE.INFPROVDESC = 0 THEN 'BASE'
            WHEN EVE.INFPROVDESC = 1 THEN 'PROVENTO'
         ELSE 'DESCONTO' END  AS TPEVENTO,
         TFO.DESCRICAO  AS ORIGEM

FROM  EFO
    JOIN EFP ON EFP.EMP_CODIGO = EFO.EMP_CODIGO AND EFP.EFO_FOL_SEQ = EFO.FOL_SEQ AND EFP.EFO_EPG_CODIGO = EFO.EPG_CODIGO
    JOIN FOL ON EFO.EMP_CODIGO = FOL.EMP_CODIGO AND EFO.FOL_SEQ = FOL.SEQ
    JOIN EPG ON EFO.EMP_CODIGO = EPG.EMP_CODIGO AND EFO.EPG_CODIGO = EPG.CODIGO
    JOIN EVE ON EVE.EMP_CODIGO = EFP.EMP_CODIGO AND EVE.CODIGO = EFP.EVE_CODIGO
    JOIN FPG ON FPG.EMP_CODIGO = EPG.EMP_CODIGO  AND FPG.FOL_SEQ = FOL.SEQ
	JOIN SEP ON SEP.EMP_CODIGO = EFO.EMP_CODIGO AND SEP.DATA = EFO.SEP_DATA AND SEP.EPG_CODIGO = EFO.EPG_CODIGO
	JOIN EST ON EST.EMP_CODIGO = SEP.EMP_CODIGO AND SEP.EST_CODIGO = EST.CODIGO
	JOIN LOT ON LOT.EMP_CODIGO = SEP.EMP_CODIGO AND LOT.CODIGO = SEP.LOT_CODIGO
	JOIN TFO ON TFO.CODIGO = FOL.FOLHA
WHERE
    FOL.ENCERRADA = 'S'
AND FOL.FOLHA IN (1)
AND EXTRACT(YEAR FROM FPG.DTFINAL) =  EXTRACT(YEAR FROM CURRENT_DATE)
AND EXTRACT(MONTH FROM FPG.DTFINAL) = EXTRACT(MONTH FROM CURRENT_DATE)-1

GROUP BY
    FOL.DTCALCULO,
    EPG.EMP_CODIGO,
	EST.CODIGO,
	EST.NOME,
	LOT.CODIGO,
	LOT.NOME,
    EFP.EVE_CODIGO,
	EVE.NOME,
	EVE.INFPROVDESC,
	TFO.DESCRICAO





"""

export = conexao_fb.executar_consulta(sql_query)

# Exibindo os resultados
# for row in resultados:
#     print(row)
